spring.application.name=backend
server.port=8081

# PostgreSQL Veritabanı Ayarları
spring.datasource.url=jdbc:postgresql://localhost:5432/codeyourtreedb
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Veritabanı tablolarını Java class'larına göre otomatik oluştur/güncelle
spring.jpa.hibernate.ddl-auto=update

# Arka planda dönen SQL sorgularını konsolda görmek için (öğrenirken çok faydalıdır)
spring.jpa.show-sql=true

# SQL sorgularını düzgün ve okunaklı formatlamak için
spring.jpa.properties.hibernate.format_sql=true
